### ISSUE TITLE
escaping inconsistent

### ISSUE THREAD

**Issue by srl295** [swagger-api/swagger-js#1220] opened 2018-01-10 17:04 UTC
We ran into an issue https://github.com/IBM-Cloud/gp-js-client/issues/113 where a path component (part of a parameter) was for example `a '` (A, space, quote).  Going into the URL Interceptor so that we can add authorization the path was escaped to a URL such as `http://example.com/api/a%20'` - so far so good. But then, when the request was actually sent, the Fetch module ran the URL through `url.parse` again, resulting in `http://example.com/api/a%20%27`.  This results in the same logical behavior, however, the exact URL string is different causing our HMAC calculation to be wrong.

I worked around this in https://github.com/IBM-Cloud/gp-js-client/pull/114/files#diff-38aee4b3886a621f8daddb4104803472R91 by having an interceptor run `url.parse()` on the URL pre-emptively before HMAC calculation, which makes the later parse a no-op. 

I was a little surprised that quote (%27) gets escaped as it is acceptable per HTTP.  Probably the larger issue is that the escaping that happens within swagger-js should match the escaping that actually goes out on the wire.

**Comment by srl295** [comment] 2018-01-10 17:21
this was observed under 3.3.1 and also `master` (so 3.4.4+)

**Comment by shockey** [comment] 2018-01-10 22:47
Thanks for the report, @srl295!

We've had this issue crop up in the past, looks like we might have a blind spot.

**Comment by srl295** [comment] 2018-01-11 18:31
```js
url.parse("http://example.com/'").href;
// --> http://example.com/%27
```

**Comment by shockey** [comment] 2018-01-12 01:33
Hmm - I'm not able to reproduce this on my end:

<img src='https://shipusercontent.com/7f9c310b116fde33446c583aeb1cc8f9/Pasted%20Image%203.png' title='Pasted Image 3.png' width=1016>

What browser are you seeing this in? I'm on macOS Chrome 63.

**Comment by srl295** [comment] 2018-01-12 02:02
@shockey this is via node.js API, not browser. And interesting, looking at your inspector… in this case though,  the HTTP request isn't wrong, the problem is that what's passed to the interceptor is **not** what goes out over the wire. The Fetch module does another escaping after the interceptor is done.

I think i can make a standalone case for it.

**Comment by shockey** [comment] 2018-01-12 02:07
Ah, got it. My hunch is that this is an implementation difference.

Looking forward to a demo for this (a failing test would be great!)

**Comment by webron** [comment] 2018-02-20 03:52
@srl295 ping? :)

**Comment by srl295** [comment] 2018-02-27 16:16
@webron pong ^

**Comment by srl295** [comment] 2018-10-19 20:18
@shockey ping ^ ?

**Comment by char0n** [comment] 2020-05-01 11:15
@srl295 thank you for reporting this and for providing a failing test.

The problem is in [node-fetch](https://github.com/node-fetch/node-fetch) library that we use when `swagger-client` is run in `node.js` runtime.

**Actual url requested in node.js**
```
fetch("http://localhost:8080/ '") -> url: /%20%27
```

**Actual url requested in browser**
```js
fetch("http://localhost:8080/ '") -> url: /%20'
```

The actual problem lies in node-fetch implementation of fetch interface. The implementation is using [legacy API](https://nodejs.org/api/url.html#url_legacy_api) instead of new [WHATWG URL API](https://nodejs.org/api/url.html#url_the_whatwg_url_api). And that is causing inconsistencies. Fortunately [node-fetch@3.0.0-beta.1](https://github.com/node-fetch/node-fetch/blob/2a61567ac3637a3332075c2c796286173ae7fd6a/docs/CHANGELOG.md#v300-beta1) swichtech to new WHATWG URL API. So the moment we switch to major version 3.x of node-fetch this issue will auto-correct.  

I'm leaving this issue open untill we update node-fetch to 3.x branch.

**Comment by char0n** [comment] 2023-09-12 07:57
Addressed in https://github.com/swagger-api/swagger-js/pull/3137/commits/f9207bd1d2663e87d10cdab7ff5b9aefe026c8fa, which is part of https://github.com/swagger-api/swagger-js/pull/3137.

Thank you for patience.

**Closed by char0n** 2023-09-12 07:57 UTC
Labels: type: bug, version: 3.x, dependencies

**Comment by srl295** [comment] 2023-09-12 08:13
@char0n thanks!
