### ISSUE TITLE
TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by jzrebiec** [swagger-api/swagger-js#3170] opened 2023-09-29 07:41 UTC
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Chrome Version 117.0.5938.62 (Official Build) (arm64), node 18.17.1
 - Method of installation: npm
 - Swagger-Client version: >= 3.1.0 (currently tested in `3.22.3`)
 - Swagger/OpenAPI version: OpenApi 3.0

### Content & configuration

Swagger-Client usage:
```js
SwaggerClient({url: '/relative-url-to/api-docs'})
```

### Describe the bug you're encountering
Since version `3.1.0` it is impossible to initialize `SwaggerClient` with a relative url.

### To reproduce...

1. Try to initialize the SwaggerClient with a relative url

### Expected behavior
The SwaggerClient works in the same way like in version `3.20.2` and eriel.

### Additional context or thoughts
```
Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL - url.mjs:214
    at Kc (url.mjs:214:35)
    at index.js:330:62
    at index.js:324:10
    at sT (index.js:284:23)
    at Object.oT [as buildRequest] (index.js:168:14)
    at uT.execute (index.js:91:24)
    at uT.execute (index.js:89:20)
    at Object.services (interfaces.js:27:24)
    at ApiHub.js:8:25
    at l (regeneratorRuntime.js:44:17)
```

It seems that the `resolve://` protocol is unknown.

**Comment by char0n** [comment] 2023-10-03 13:56
Hi @jzrebiec,

Yep, this is a legit regression. We need to make the url absolute in browser env right after passing the `url` option in.

**Comment by char0n** [comment] 2023-10-04 15:52
@jzrebiec as a workaround for now, can you do the following?

```js
const url = String(new URL('/relative-url-to/api-docs', document.baseURI));
SwaggerClient({url });
```

**Comment by albatross36** [comment] 2023-10-10 04:35
This issue is also affecting [swagger-ui](https://github.com/swagger-api/swagger-ui), since it uses "swagger-client": "^3.23.0".

**Comment by char0n** [comment] 2023-10-10 05:42
@albatross36 thanks I'll address the swagger-ui-react as well.

**Comment by ItsReddi** [comment] 2023-10-10 07:32
Thanks for the workaround @char0n should we wait for the version that fixes this BC or going with the workaround for now?

**Comment by char0n** [comment] 2023-10-10 08:00
Still thinking about how to approach this. SwaggerClient is isomorphic, which means it runs in Node.js and browser env. I consider prior supporting of `relative URI Reference` in here a **bug**. If the code runs in Node.js environment, there is no way to construct the absolute `retrievalURI` need for proper OpenAPI dereference purposes. So for the matter of consistency, SwaggerClient should only consume absolute URLs. If you want to construct relative URI References in browser env in lazy manner, then the workaround mentioned in https://github.com/swagger-api/swagger-js/issues/3170#issuecomment-1747192897 is a way to go.

> This issue is also affecting [swagger-ui-react](https://github.com/swagger-api/swagger-ui), since it uses "swagger-client": "^3.23.0" as a dependency.

Regarding `swagger-ui` - this has already been resolved couple of releases before - as the SwaggerUI is meant only for browser env, we make any URL absolute before we pass it to swagger-client.

 Regarding `swagger-ui-react` again it's problematic  as it support SSR (Server Side Rendering). And during the SSR we don't have access to `document` object obviously. But we can probably do something like following in there:

```js
if (typeof document !== 'undefined') {
  url = String(new URL(url, document.baseURI));
}
```

Any opinion is welcome.

**Comment by ItsReddi** [comment] 2023-10-11 08:38
From our side we are using the client only in browser envs so it is fine for us. To consider to relative URI support as a bug before.
But.. i am confused, SwaggerClient was isomorphic before.
And it worked. So what was changed that this is not working anymore / why it is not possible to reproduce the old behavior?

Because of that i considered it as a BC.

**Comment by char0n** [comment] 2023-10-11 17:09
Right so here is the explanation:

> SwaggerClient was isomorphic before.

Yes, but since [v3.21.0](https://github.com/swagger-api/swagger-js/releases/tag/v3.21.0) we've removed obscure and deprecated URL parser and replaced it with [WhatWG URL standard](https://url.spec.whatwg.org/) parser, which basically means we're using [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) global symbol to parse any URI. This parser is not capable to resolve one relative URL against another relative URL. That's why we're seeing this error now. I did many contingencies to make the behavior fully backward compatible but I've missed this one.

 So if you call `SwaggerClient({url: '/relative-url-to/api-docs'})` in browser context, this relative URL is passed to [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) which in browser context basically does `String(new URL(relativeURL, document.baseURI))` (the same way as <a> relative links are created). This resolution to absolute URL is implicit and the rest of swagger-client code works further with the original relative URL, and as explained above it eventually fail as resolving relative URL against another is just not possible. Just a note here: Node.js `fetch` native implementation doesn't do this implicit conversion to absolute URL.

Swagger-client versions prior to `v3.21.0`, worked until your definition contained following reference:

```yaml
  $ref: "./path/openapi.json#components/schema1"
```

As you originally provided relative reference and the `$ref` contains again relative reference, swagger-client cannot determine the absolute form of the `$ref` and throws an exception.

So technically relative URL References never worked properly.

I think I can do simple change that will allow to pass relative URL Reference in browser environment and and resolve the `$ref` defined as relative URL Reference correctly.

**Comment by char0n** [comment] 2023-10-11 18:02
Addressed in https://github.com/swagger-api/swagger-js/pull/3177

```
In browser environment, we allow to pass a relative URI Reference, and we resolve it against the document's baseURI before passing it deeper to swagger-client code. This also addressed issue of ignored `$ref` - all references are now resolved properly.

**Comment by char0n** [comment] 2023-10-11 18:48
Released as https://github.com/swagger-api/swagger-js/releases/tag/v3.23.1

**Closed by char0n** 2023-10-11 18:48 UTC
Labels: type: regression, version: 3.x

**Comment by adoma333** [comment] 2024-11-19 14:12
HI
