### ISSUE TITLE
nvm/node unsupported warning

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-js#1723] opened 2020-09-18 20:45 UTC
### Q&A (please complete the following information)
 - OS:  macOS
 - Environment: nvm@13.9.0
 - Method of installation: npm
 - Swagger-Client version: 3.11.0
 - Swagger/OpenAPI version: n/a

### Describe the bug you're encountering

```
npm WARN notsup Unsupported engine for swagger-client@3.11.0: wanted: {"node":">=10.21.0","npm":">=6.14.5"} (current: {"node":"13.9.0","npm":"6.13.7"})
npm WARN notsup Not compatible with your version of node/npm: swagger-client@3.11.0

```

### To reproduce...

1. clone swagger-editor project
2. npm i
3. see warnings above

### Expected behavior

No errors or warnings when using later major/minor versions of nvm/node.

### Additional context or thoughts

This was discovered while prepping for swagger-editor@3.14.0 release on local

**Comment by char0n** [comment] 2020-09-21 11:47
@tim-lai this is duplicate of https://github.com/swagger-api/swagger-js/issues/1684. We already know about this issue and the only way to solve this for npm and yarn simultaneously is to remove the `engines` field. Please follow the reasoning discussion in  https://github.com/swagger-api/swagger-js/issues/1684

**Closed by char0n** 2020-09-21 11:47 UTC
