### ISSUE TITLE
Client throws error with this spec

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-js#324] opened 2015-03-26 18:14 UTC
```json
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "Place Kitten"
    },
    "host": "placekitten.com",
    "basePath": "/200",
    "paths": {
        "/300": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}
```

Error:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
swagger-ui.js:1670 3.SwaggerClient.idFromOpswagger-ui.js:1538 (anonymous function)swagger-ui.js:15629 arrayEachswagger-ui.js:15500 forEachswagger-ui.js:1519 (anonymous function)swagger-ui.js:15949 baseForswagger-ui.js:15991 baseForOwnswagger-ui.js:15884 baseEachswagger-ui.js:15501 forEachswagger-ui.js:1513 3.SwaggerClient.buildFromSpecswagger-ui.js:2164 6.Resolver.resolveswagger-ui.js:1407 3.SwaggerClient.build.obj.on.responseswagger-ui.js:2001 (anonymous function)swagger-ui.js:19629 98.Request.callbackswagger-ui.js:19281 (anonymous function)swagger-ui.js:20032 99.Emitter.emitswagger-ui.js:19701 98.Request.end.xhr.onreadystatechange
```

```
SwaggerClient.prototype.idFromOp = function (path, httpMethod, op) {
  var opId = op.operationId.replace(/[\s!@#$%^&*()_+=\[{\]};:<>|.\/?,\\'""-]/g, '_') || (path.substring(1) + '_' + httpMethod);

  opId = opId.replace(/((_){2,})/g, '_');
  opId = opId.replace(/^(_)*/g, '');
  opId = opId.replace(/([_])*$/g, '');
  ret....
```

**Comment by whitlockjc** [comment] 2015-03-26 18:25
This is a duplicate of #322.

**Closed by whitlockjc** 2015-03-26 18:25 UTC
