### ISSUE TITLE
test: existing http test fails on node v10+

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-js#1528] opened 2020-05-05 21:31 UTC
### Q&A (please complete the following information)
 - OS:  macOS 10.15.3
 - Environment:  Node.js v10.19.0, Node.js v13.9.0
 - Method of installation: npm
 - Swagger-Client version: 3.10.0
 - Swagger/OpenAPI version: n/a

### Content & configuration

n/a. uses existing unit tests.

### Describe the bug you're encountering

This test passes on Node 8, but fails on Node 10+.

```
 FAIL  test/client.js
  ● http › should err gracefully when requesting https from an http server

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    - request to https://localhost:8000/petstore.json failed, reason: socket hang up
    + request to https://localhost:8000/petstore.json failed, reason: write EPROTO 4464160192:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
    +

      281 |       }
      282 |     }).catch((err) => {
    > 283 |       expect(err.message).toEqual(
          |                           ^
      284 |         'request to https://localhost:8000/petstore.json failed, reason: socket hang up'
      285 |       )
      286 |     })

      at test/client.js:283:27
```

### To reproduce...

1. `npm run test:unit1

### Expected behavior

This existing test should pass on Node 10+. 

### Additional context or thoughts

Deprecate Node 8 support is acceptable, which requires CI env update.

**Comment by char0n** [comment] 2020-05-06 09:06
Are you running your tests on current master? If you run the tests on your branch `tim-lai:bug/1526-multipart` I can see that this branch is not rebased on current upstream master.

This ticket has already been resolved in https://github.com/swagger-api/swagger-js/issues/1511 a week ago. 

Closing as duplicate of #1511 and #1447

**Closed by char0n** 2020-05-06 09:06 UTC
