### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by erajkovic** [swagger-api/swagger-js#1077] opened 2017-06-08 17:13 UTC
With latest version of swagger UI, getting same error as reported in issue #720 - the same swagger file was properly loaded in older version of swagger UI.

Resolver error
Cannot read property '0' of undefined

To reproduce, load https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/compute/1.0/apis/VirtualNICs/canonical in http://petstore.swagger.io/ 

Thanks,
-Eric

**Comment by webron** [comment] 2017-06-08 22:47
Looks like this is a result of a psuedo-circular reference, that shouldn't even be resolved.

**Comment by etki** [comment] 2017-11-29 10:27
Having the same issue (with pseudo-circular reference as well). I have Region that may have itself in parents (renders as null, and that's okay with me), but when another entity is present (SubwayStation that also lists regions in parents), error strikes in; whenever i drop `parents` property from any of them, error goes. Sadly couldn't reproduce in a minimal example.

**Comment by san4io** [comment] 2017-12-03 22:19
Same for me then updated to 3.6.0.

Downgraded: 
        "swagger-api/swagger-ui": "3.5.0"

**Comment by shockey** [comment] 2017-12-04 23:19
@san4io, can you provide your API definition? If it worked in 3.5.0, there may be a regression that we need to look into, but we can't do that without something to test with :smile:

**Comment by rusinv** [comment] 2017-12-15 09:19
Having similar issue (as I suppose): "Cannot read property '/route' of undefined":
```
openapi: 3.0.0
info: 
  version: '0.1'
  title: 'test'

paths:

  /route:
    get:
      responses:
        '200':
          description: Descr
          content:
            'application/json':
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessfulResponseContainer'
                properties:
                  payload:
                    $ref: '#/components/schemas/PayloadContents'

components:
  schemas:
    ResponseContainer:
      type: object
      properties:
        type:
          type: integer
        payload:
          type: object

    SuccessfulResponseContainer:
      allOf:
        - $ref: '#/components/schemas/ResponseContainer'
      properties:
        type:
          type: integer

    Payload:
      type: object
      properties:
        prop1:
          type: string

    PayloadContents:
      type: object
      allOf:
        - $ref: '#/components/schemas/Payload'
      properties:
        prop2:
          type: string
```
Error disappears if I reduce depth of inheritance:

```
...
    PayloadContents:
      type: object
      #allOf:
       # - $ref: '#/components/schemas/Payload'
      properties:
        prop2:
          type: string
...
```

**Comment by san4io** [comment] 2017-12-15 14:15
Sorry, was on vacation, today I'll provide you with json.

**Comment by san4io** [comment] 2017-12-16 21:36
{"swagger":"2.0","info":{"title":"Accommobay API","version":"1.0.0"},"basePath":"\/v1\/","consumes":["application\/json"],"produces":["application\/json"],"paths":{"\/auth\/password\/forgot":{"post":{"tags":["1. Auth API"],"summary":"Forgotten User password","description":"Send email to user with reset link","operationId":"forgotten_password","consumes":["multipart\/form-data"],"produces":["application\/json"],"parameters":[{"name":"email","in":"formData","description":"User email","required":true,"type":"string"}],"responses":{"200":{"description":"Successful Operation"},"422":{"description":"Wrong Email address"}}}},"\/auth\/authenticate":{"post":{"tags":["1. Auth API"],"summary":"Authenticate User","description":"Authenticate user","operationId":"authenticate","consumes":["multipart\/form-data"],"produces":["application\/json"],"parameters":[{"name":"email","in":"formData","description":"User email","required":true,"type":"string"},{"name":"password","in":"formData","description":"User password","required":true,"type":"string"}],"responses":{"200":{"description":"Successful Operation"}}}},"\/auth\/me":{"get":{"tags":["1. Auth API"],"summary":"Get current user info","description":"Returns user info by authorization header","operationId":"user_me","produces":["application\/json"],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/User"}}},"security":[{"bearer_token":[]}]}},"\/auth\/token\/refresh":{"post":{"tags":["1. Auth API"],"summary":"Refresh User Token","description":"Refresh user token","operationId":"user_refresh","consumes":["multipart\/form-data"],"produces":["application\/json"],"parameters":[{"name":"token","in":"formData","description":"User refresh token","required":true,"type":"string"}],"responses":{"200":{"description":"Successful Operation"}}}},"\/auth\/register":{"post":{"tags":["1. Auth API"],"summary":"Register User","description":"Register user","operationId":"register","consumes":["multipart\/form-data"],"produces":["application\/json"],"parameters":[{"name":"name","in":"formData","description":"User name","required":true,"type":"string"},{"name":"surname","in":"formData","description":"User surname","required":true,"type":"string"},{"name":"email","in":"formData","description":"User email","required":true,"type":"string"},{"name":"password","in":"formData","description":"User password","required":true,"type":"string"},{"name":"password_confirmation","in":"formData","description":"User password confirmation","required":true,"type":"string"},{"name":"phone","in":"formData","description":"User phone","required":false,"type":"string"},{"name":"country_id","in":"formData","description":"User country id","required":false,"type":"string"}],"responses":{"200":{"description":"Successful Operation"}}}},"\/auth\/password\/reset":{"post":{"tags":["1. Auth API"],"summary":"Reset User password","description":"Resets user password","operationId":"reset_password","consumes":["multipart\/form-data"],"produces":["application\/json"],"parameters":[{"name":"email","in":"formData","description":"User email","required":true,"type":"string"},{"name":"password","in":"formData","description":"User password","required":true,"type":"string"},{"name":"password_confirmation","in":"formData","description":"User password confirmation","required":true,"type":"string"},{"name":"token","in":"formData","description":"Reset password token","required":true,"type":"string"}],"responses":{"200":{"description":"Successful Operation"},"401":{"description":"Unauthorized"}}}},"\/claims":{"get":{"tags":["3. Claim API"],"summary":"Get Claim List","description":"Retrieve own claims","operationId":"claims","produces":["claim\/json"],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/OwnPaginatedClaim"}}},"security":[{"bearer_token":[]}]},"post":{"tags":["3. Claim API"],"summary":"Create new Claim object","description":"Creates and returns Claim","operationId":"claim_create","produces":["claim\/json"],"parameters":[{"name":"body","in":"body","description":"Claim object","required":true,"schema":{"$ref":"#\/definitions\/Claim"}}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/Claim"}}},"security":[{"bearer_token":[]}]}},"\/claims\/{claim-id}":{"get":{"tags":["3. Claim API"],"summary":"Get Claim by it's ID","description":"Returns Claim and related info","operationId":"claim_get","produces":["claim\/json"],"parameters":[{"name":"claim-id","in":"path","description":"ID of claim","required":true,"type":"string","format":"string"}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/OwnClaimList"}}},"security":[{"bearer_token":[]}]},"put":{"tags":["3. Claim API"],"summary":"Update an existing Claim","description":"Update Claim","operationId":"claim_update","parameters":[{"name":"claim-id","in":"path","description":"ID of Claim","required":true,"type":"string","format":"string"},{"name":"body","in":"body","description":"Place object that needs to be updated","required":true,"schema":{"$ref":"#\/definitions\/Claim"}}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/Claim"}}},"security":[{"bearer_token":[]}]},"delete":{"tags":["3. Claim API"],"summary":"Remove Claim","description":"Removes Claim, only owner of Claim can remove it.","operationId":"claim_destroy","produces":["claim\/json"],"parameters":[{"name":"claim-id","in":"path","description":"Claim id to delete","required":true,"type":"string","format":"string"}],"responses":{"200":{"description":"Removed successfully"}},"security":[{"bearer_token":[]}]}},"\/claims\/confirm\/{claim-id}":{"post":{"tags":["3. Claim API"],"summary":"Confirm claim","description":"Confirms Claim","operationId":"claim_confirm","produces":["claim\/json"],"parameters":[{"name":"claim-id","in":"path","description":"ID of Claim","required":true,"type":"string","format":"string"}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/Claim"}}},"security":[{"bearer_token":[]}]}},"\/oauth\/personal-access-tokens":{"get":{"tags":["5. OAuth API"],"summary":"Get Personal Tokens","description":"Retrieve personal tokens","operationId":"tokens_get","produces":["application\/json"],"responses":{"200":{"description":"List retrieved successfully"}},"security":[{"bearer_token":[]}]},"post":{"tags":["5. OAuth API"],"summary":"Get Personal Tokens","description":"Retrieve personal tokens","operationId":"tokens_get","produces":["application\/json"],"parameters":[{"name":"body","in":"body","description":"Claim object","required":true,"schema":{"$ref":"#\/definitions\/Token"}}],"responses":{"200":{"description":"Token created successfully"}},"security":[{"bearer_token":[]}]}},"\/oauth\/personal-access-tokens\/{token-id}":{"delete":{"tags":["5. OAuth API"],"summary":"Remove Personal Token","description":"Remove personal tokens","operationId":"tokens_delete","produces":["application\/json"],"parameters":[{"name":"token-id","in":"path","description":"Token id to delete","required":true,"type":"string","format":"string"}],"responses":{"200":{"description":"Removed successfully"}},"security":[{"bearer_token":[]}]}},"\/places":{"get":{"tags":["2. Place API"],"summary":"Get Own Place List","description":"Retrieve own places","operationId":"places_own","produces":["application\/json"],"parameters":[{"name":"query","in":"query","description":"Searchable string","required":false,"type":"string"}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/PaginatedPlace"}}},"security":[{"bearer_token":[]}]},"post":{"tags":["2. Place API"],"summary":"Create new Place object","description":"Creates and returns Place","operationId":"place_create","produces":["application\/json"],"parameters":[{"name":"body","in":"body","description":"Offer object","required":true,"schema":{"$ref":"#\/definitions\/Place"}}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/Place"}}},"security":[{"bearer_token":[]}]}},"\/places\/{place-id}":{"get":{"tags":["2. Place API"],"summary":"Get Place by it's ID","description":"Returns Place and related info","operationId":"place_get","produces":["application\/json"],"parameters":[{"name":"place-id","in":"path","description":"ID of place","required":true,"type":"string","format":"string"}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/Place"}}}},"put":{"tags":["2. Place API"],"summary":"Update an existing Place","description":"Update Place","operationId":"place_update","parameters":[{"name":"place-id","in":"path","description":"ID of Place","required":true,"type":"string","format":"string"},{"name":"body","in":"body","description":"Place object that needs to be updated","required":true,"schema":{"$ref":"#\/definitions\/Place"}}],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/Place"}}},"security":[{"bearer_token":[]}]},"delete":{"tags":["2. Place API"],"summary":"Remove Place","description":"Removes Place, only owner of tender can remove it.","operationId":"place_destroy","produces":["application\/json"],"parameters":[{"name":"place-id","in":"path","description":"Place id to delete","required":true,"type":"string","format":"string"}],"responses":{"200":{"description":"Removed successfully"}},"security":[{"bearer_token":[]}]}},"\/places\/search":{"post":{"tags":["2. Place API"],"summary":"Get Place List","description":"Retrieve all places","operationId":"places","produces":["application\/json"],"responses":{"200":{"description":"successful operation","schema":{"$ref":"#\/definitions\/PaginatedPlace"}}}}},"\/utils\/address":{"get":{"tags":["4. Utils API"],"summary":"Get Address suggestions","description":"Get Address suggestions","operationId":"address","produces":["application\/json"],"parameters":[{"name":"q","in":"query","description":"Search query","required":true,"type":"string"},{"name":"limit","in":"query","description":"Limit","type":"integer"},{"name":"country_code","in":"query","description":"Country code","type":"string"}],"responses":{"200":{"description":"successful operation","schema":{"type":"array","items":{"$ref":"#\/definitions\/GeoBag"}}}}}},"\/utils\/countries":{"get":{"tags":["4. Utils API"],"summary":"Get Countries List","description":"Retrieve all countries","operationId":"types","produces":["application\/json"],"responses":{"200":{"description":"successful operation","schema":{"type":"array","items":{"$ref":"#\/definitions\/Country"}}}}}},"\/utils\/types":{"get":{"tags":["4. Utils API"],"summary":"Get Types List","description":"Retrieve all types","operationId":"types","produces":["application\/json"],"responses":{"200":{"description":"successful operation","schema":{"type":"array","items":{"$ref":"#\/definitions\/Type"}}}}}}},"definitions":{"Answer":{"properties":{"answer":{"description":"Place name","type":"string","format":"string","example":"Not smoking"},"question_id":{"description":"Question id","type":"integer","format":"number","example":4}}},"Claim":{"properties":{"id":{"description":"Place id","type":"integer","format":"integer","example":1},"place_id":{"description":"Place id","type":"integer","format":"integer","example":1},"user_id":{"description":"Place id","type":"integer","format":"integer","example":1},"created_at":{"description":"Place creation date","type":"string","format":"string","example":"2017-09-16 21:51:59"},"updated_at":{"description":"Place was updated","type":"string","format":"string","example":"2017-09-16 21:51:59"},"answers":{"type":"array","items":{"$ref":"#\/definitions\/Answer"}}}},"OwnClaimList":{"properties":{"place":{"$ref":"#\/definitions\/Place"}},"type":"object","allOf":[{"$ref":"#\/definitions\/Claim"}]},"ClaimList":{"properties":{"user":{"$ref":"#\/definitions\/User"}},"type":"object","allOf":[{"$ref":"#\/definitions\/OwnClaimList"}]},"OwnPaginatedClaim":{"properties":{"data":{"type":"array","items":{"$ref":"#\/definitions\/OwnClaimList"}},"path":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/application"},"first_page_url":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/application?page=1"},"last_page_url":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/application?page=10"},"next_page_url":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/application?page=3"},"prev_page_url":{"type":"number","format":"string","example":"http:\/\/localhost\/api\/v1\/application?page=1"}},"type":"object","allOf":[{"$ref":"#\/definitions\/pagination"}]},"Country":{"properties":{"id":{"description":"Country id","type":"integer","format":"integer","example":1},"code":{"description":"Country code","type":"string","format":"string","example":"LV"},"name":{"description":"Country name","type":"string","format":"string","example":"Latvia (Latvija)"},"common":{"description":"Country common name","type":"string","format":"string","example":"Latvia"},"currency":{"description":"Country currency","type":"string","format":"string","example":"EUR"},"call_code":{"description":"Country call code","type":"string","format":"string","example":"+371"}}},"Place":{"properties":{"id":{"description":"Place id","type":"integer","format":"integer","example":1},"title":{"description":"Place name","type":"string","format":"string","example":"Best room in the world"},"address":{"description":"Place address","type":"string","format":"string","example":"Fabijoni\u0161ki\u0173 g. 15, Vilnius"},"description":{"description":"Place email","type":"string","format":"string","example":"Best room in the world description"},"price":{"description":"Place price","type":"string","format":"string","example":25.95},"area":{"description":"Place area in m^2","type":"string","format":"string","example":25.24},"rooms":{"description":"Place rooms","type":"string","format":"string","example":2},"bathrooms":{"description":"Place rooms","type":"string","format":"string","example":1},"floor":{"description":"Place floors","type":"string","format":"string","example":3},"floor_count":{"description":"Building floors","type":"string","format":"string","example":8},"year":{"description":"Place year of build","type":"string","format":"string","example":2016},"action":{"description":"Place for rent or sell","type":"string","format":"string","example":1},"type_id":{"description":"Place type","type":"string","format":"string","example":2},"country_id":{"description":"Place country","type":"string","format":"string","example":101},"location":{"$ref":"#\/definitions\/location"},"created_at":{"description":"Place creation date","type":"string","format":"string","example":"2017-09-16 21:51:59"},"updated_at":{"description":"Place was updated","type":"string","format":"string","example":"2017-09-16 21:51:59"}}},"PaginatedPlace":{"properties":{"data":{"type":"array","items":{"$ref":"#\/definitions\/Place"}},"path":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/place"},"first_page_url":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/place?page=1"},"last_page_url":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/place?page=10"},"next_page_url":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/place?page=3"},"prev_page_url":{"type":"number","format":"string","example":"http:\/\/localhost\/api\/v1\/place?page=1"}},"type":"object","allOf":[{"$ref":"#\/definitions\/pagination"}]},"Type":{"properties":{"id":{"description":"Type id","type":"integer","format":"integer","example":1},"name":{"description":"Type name","type":"string","format":"string","example":"room_rent"}}},"User":{"properties":{"id":{"description":"User id","type":"integer","format":"integer","example":1},"name":{"description":"User name","type":"string","format":"string","example":"Zbignev"},"surname":{"description":"User surname","type":"string","format":"string","example":"Balcevi\u010d"},"email":{"description":"User email","type":"string","format":"string","example":"zbignev@mail.pl"},"country_id":{"description":"User email","type":"string","format":"string","example":96},"phone":{"description":"User phone","type":"string","format":"string","example":"+37060674779"},"created_at":{"description":"User creation date","type":"string","format":"string","example":"2017-09-16 21:51:59"},"updated_at":{"description":"User updated at","type":"string","format":"string","example":"2017-09-16 21:51:59"}}},"GeoBag":{"properties":{"formatted":{"description":"Fabijoni\u0161ki\u0173 g., Fabijoni\u0161ki\u0173 seni\u016bnija, Vilnius, Vilnius city municipality, Vilnius County, 06328, Lithuania","type":"string","format":"string","example":""},"coordinates":{"description":"Location of the value. Latitude, Longitude","type":"number","format":"double","maxItems":2,"minItems":2,"example":[48.870465,2.351447]}}},"pagination":{"properties":{"current_page":{"type":"number","format":"integer","example":2},"from":{"type":"number","format":"integer","example":16},"last_page":{"type":"number","format":"integer","example":10},"per_page":{"type":"number","format":"integer","example":15},"to":{"type":"number","format":"integer","example":30},"total":{"type":"number","format":"integer","example":150},"path":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/entity"},"first_page_url":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/entity?page=1"},"last_page_url":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/entity?page=10"},"next_page_url":{"type":"string","format":"string","example":"http:\/\/localhost\/api\/v1\/entity?page=3"},"prev_page_url":{"type":"number","format":"string","example":"http:\/\/localhost\/api\/v1\/entity?page=1"}},"type":"object"},"location":{"properties":{"type":{"description":"GeoJson point","type":"string","format":"string","example":"Point"},"coordinates":{"description":"Location of the value. Latitude, Longitude","type":"number","format":"double","maxItems":2,"minItems":2,"example":[48.870465,2.351447]}}},"Token":{"properties":{"name":{"type":"string","format":"string","example":"My Token"},"scopes":{"type":"array","format":"array","items":{}}}}},"externalDocs":{"description":"GeoJson Objects","url":"http:\/\/geojson.org\/"},"securityDefinitions":{"bearer_token":{"type":"apiKey","description":"OAuth 2.0 Laravel Passport authorization","name":"Authorization","in":"header"}}}

**Comment by jeff9finger** [comment] 2018-01-17 21:54
I am having this issue as well, with swagger-ui 3.9.1 which uses swagger-js (swagger-client) 3.4.5.

**Comment by erajkovic** [comment] 2018-03-06 20:23
I am still having the issue with the latest swagger ui - we are on 3.9.1 now (see https://apicatalog.oraclecloud.com/ui/views/swaggerui3/oracle-public/compute/default/SecIPLists) , and I tested internally with 3.10.0

**Comment by shockey** [comment] 2018-03-06 20:27
@erajkovic can you try with UI 3.12.0 as well?

Take note that resolution happens on model/operation expansion now, so you may need to manually expand your document to see if the error arises.

**Comment by erajkovic** [comment] 2018-03-06 20:35
@shockey will try and report back - was having similar issue with named properties, so will see if they are all gone with latest.
The other error message was: Cannot read property 'userEvent' of undefined, which seams to match the forward reference case.

**Comment by jeff9finger** [comment] 2018-03-07 00:05
UI 3.12.0 resolved the issue for me. 👍

**Comment by erajkovic** [comment] 2018-03-07 03:54
Is it OK to have a new side effect - now the URL contains a query parameter : http://localhost:9080/ui/views/swaggerui3/oracle-public/compute/default/RebootInstanceRequests?urls.primaryName=RebootInstanceRequests 
I guess this would be a separate issue / maybe this is something we have to handle on our side with a wrappedAction.
So, in short +1 - UI 3.12.0 resolved the issue for me too.

**Comment by shockey** [comment] 2018-03-07 04:56
> So, in short +1 - UI 3.12.0 resolved the issue for me too.

Wonderful! I'll close this issue out then.

> Is it OK to have a new side effect - now the URL contains a query parameter

Yes, that was introduced in 3.12.0 for folks using the Standalone preset and the `urls` parameter - it's to keep track of the currently selected option so that the UI stays consistent across refreshes. It's not currently possible to turn that off - if you'd like to have the option, please open a ticket for that!

**Closed** 2018-03-07 04:56 UTC
Labels: P2, type: bug, version: 3.x
