### ISSUE TITLE
Dropdown for enum doesn't display correctly when it's set as a required parameter

### ISSUE THREAD

**Issue by ianchadwick** [swagger-api/swagger-js#391] opened 2015-04-25 19:12 UTC
See screen shot below, when a parameter that has enum is set to required the name is repeated in the 2nd column which breaks the formatting.

![Alt text](http://s22.postimg.org/e1otopue9/Screen_Shot_2015_04_25_at_20_05_29.png)

Here's the parameter snippet

```javascript
{
  name: "type",
  in: "formData", 
  description: "Lead type",
  required: true,
  type: "array",
  items: {
    type: "string"
  },
  collectionFormat: "multi",
  enum: [
    "pba",
    "ppi",
    "investment"
  ]
}
```

**Comment by webron** [comment] 2015-04-26 09:17
Duplicate of https://github.com/swagger-api/swagger-ui/issues/1113.

**Closed by webron** 2015-04-26 09:17 UTC
