### ISSUE TITLE
upgrade to v3.16.0 broke swagger client call to file upload endpoint

### ISSUE THREAD

**Issue by opadilla** [swagger-api/swagger-js#2209] opened 2021-08-31 16:50 UTC
- OS: node:14.16.1 docker image
 - Environment: node:14.16.1
 - Method of installation: npm
 - Swagger-Client version: 3.16.0
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
...
  /api/files/{parentFolder}/{path}/upload/internal:
    post:
      tags:
        - "files"
      security:
        - integrifyEnvToken: []
      summary: "upload file"
      operationId: "internalUploadFile"
      parameters:
        - name: parentFolder
          required: true
          in: path
          schema:
            type: string
            enum: [attachments, config, reports, temp, logs]
        - name: path
          required: true
          in: path
          schema:
            type: string
        - name: tenant
          required: true
          in: query
          schema:
            type: string
      requestBody:
        content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: string
                      format: binary
      responses:
        200:
          description: "success"
          content:
            application/json:
              schema:
                type: object
        400:
          description: "invalid"
        500:
          description: "an error occured processing your request"
...
```

Swagger-Client usage:
```js
async getClient(service, bearerToken) {
    const portalUrl = await this._getPortalUrl()

    let authorizations = {
      integrifyEnvToken: process.env.INTEGRIFY_ENV_TOKEN
    }

    if (bearerToken) {
      authorizations.bearerAuth = bearerToken
    }

    const client = await SwaggerClient({
      url: await this._getSwaggerEndpoint(service),
      authorizations
    })

    return client
  }
...
...
  async saveToFileStore(sourcePath, targetPath) {
    const slashIdx = targetPath.indexOf(path.sep);
    const parentFolder = targetPath.substring(0, slashIdx);
    const filePath = targetPath.substring(slashIdx);

    const fileStream = fs.createReadStream(sourcePath);

    const filesClient = await serviceClient.getClient('files') 
    const result = await filesClient.apis.files.internalUploadFile({
      parentFolder,
      path: filePath,
      tenant: this.oauth.tenant
    }, {
      requestBody: [fileStream]
    })

    return result.obj
  }
```

### Describe the bug you're encountering
This worked in swagger-js version 3.15.0.   Broke when upgraded to 3.16.0.   Just trying to upload a file to a swagger endpoint by creating a read stream.  No change in calling code.  Just swagger-js.

### To reproduce...

Use swagger-js to call a file upload endpoint from node.  The file to be uploaded is in the file system.  From what I can tell by debugging, the file isn't in the http request when using v3.16.0.

### Additional context or thoughts
Looks like the change to 3.16.0 also changed the versions of form-data-encoder and formdata-node.  Maybe the underlying problem is with those libs?

**Comment by jk0209** [comment] 2021-09-03 09:23
Similar issue. 
Getting error:
`ReferenceError: TextEncoder is not defined at new FormDataEncoder `

**Comment by char0n** [comment] 2021-09-06 06:36
@opadilla thanks for reporting this. I'm currently investigating what caused the regression.

@octet-stream - FYI we're having regressions here after formdata-node@v4

**Comment by octet-stream** [comment] 2021-09-06 10:13
In v4 I have removed ReadStream support because on browser side FormData expects a value to be string, File or Blob. To keep using files from fs, you need to replace ReadStream with fileFromPash or fileFromPath utilities, they will create a File from ReadStream.

**Comment by char0n** [comment] 2021-09-06 10:15
Here is the result of the investigation:

We've moving to fully spec compliant version of [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData). The underlying library that we used under the hood supported non-spec compliant objects like Buffers and Node.js ReadStream. In it's new version (v4) it doesn't support Buffer and ReadStream any more. And that's the problem in this issue. We didn't anticipated for SwaggerClient consumers to use the library in this way -  passing a ReadStream as a value to the FormData.

To get around this issue please use the following workaround:

```js
const { fileFromPathSync } = require('formdata-node/file-from-path');
// const { fileFromPathSync } = require('formdata-node/lib/cjs/fileFromPath'); // use this if above doesn't work

 async saveToFileStore(sourcePath, targetPath) {
    const slashIdx = targetPath.indexOf(path.sep);
    const parentFolder = targetPath.substring(0, slashIdx);
    const filePath = targetPath.substring(slashIdx);

    const file = fileFromPathSync(sourcePath);

    const filesClient = await serviceClient.getClient('files') 
    const result = await filesClient.apis.files.internalUploadFile({
      parentFolder,
      path: filePath,
      tenant: this.oauth.tenant
    }, {
      requestBody: [file]
    })

    return result.obj
  }




Attached PR with test cases demonstrating how to use `fileFromPathSync`: https://github.com/swagger-api/swagger-js/pull/2219/files#diff-9c4230679d2ed69b9b455efe9fcbf0e2e9de932ac9cbf991247f038eb43c6618R263

**Comment by octet-stream** [comment] 2021-09-06 11:35
@jk0209 in your case you probably need to inject `TextEncoder` onto `globalThis`. I assume developers will run their code in the environment that has this class.

**Comment by char0n** [comment] 2021-09-10 07:29
Assuming that this has been resolved with proposed workaround. Again, thanks for reporting this and closing for now.

**Closed by char0n** 2021-09-10 07:29 UTC
Labels: type: bug, type: regression, version: 3.x

**Comment by opadilla** [comment] 2021-09-10 15:20
Sorry I didn't get back to you.   The workaround resolved it.  Thanks!
