### ISSUE TITLE
How to use SwaggerClient in web worker

### ISSUE THREAD

**Issue by tmkasun** [swagger-api/swagger-js#2008] opened 2021-04-01 04:56 UTC
I'm getting 

```js
browser.js:1 Uncaught ReferenceError: window is not defined
```

This exception is coming from 
`swagger-client -> HTTP -> form-data-monkey-patch -> isomorphic-form-data)`

Exception when trying to use SwaggerClient in a web worker. I did a little bit of a search and found that there is an [issue created](https://github.com/form-data/isomorphic-form-data/issues/5) in `isomorphic-form-data` repo asking for a solution.

I tried setting [outputglobalobject](https://webpack.js.org/configuration/output/#outputglobalobject) in webpack output also, But that didn't work.

### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Chrome Version 89.0.4389.90 
 - Method of installation: npm
 - Swagger-Client version: 3.12.0
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration

Swagger/OpenAPI definition:

[Link to definition](https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml)

Swagger-Client usage:
```js
import SwaggerClient from 'swagger-client';

SwaggerClient.resolve({
    url: '/api/am/publisher/v2/swagger.yaml',
    requestInterceptor: (request) => {
        request.headers.Accept = 'text/yaml';
    },
}).then((spec) => {
    self.postMessage(spec);
});
```

### Screenshots

![image](https://user-images.githubusercontent.com/3313885/113243244-472e4680-92d0-11eb-84b4-0b85b9d02749.png)

### How can we help?

Can you please help me in using the SwaggerClient in the work environment? Is SwaggerClient support it or am I doing anything wrong here?

**Comment by char0n** [comment] 2021-04-01 14:51
swagger-js should work properly in Web Worker environment. The problem is (as you already mentioned correctly in this issue) `isomorphic-form-data` library that we use. Let's continue the discussion there, becase this problem needs to be fix upstream before it's fixed in swagger-js.

**Comment by char0n** [comment] 2021-04-01 14:57
Added a [comment](https://github.com/form-data/isomorphic-form-data/issues/5#issuecomment-811963897) in `isomorphic-form-data`. If it's not going to be resolved there in some reasonable time, we'll have to find an alternative solution to move things forward.

**Comment by char0n** [comment] 2021-04-05 14:23
@tmkasun,

Current workaround could be to use [resolve alias](https://webpack.js.org/configuration/resolve/#resolvealias) in your webpack config to get around this problem.

**Webpack config**
```js
...
resolve: {
  alias: {
    'isomorphic-form-data': path.resolve(__dirname, 'src/isomorphic-form-data.js/')
  }
}   
...
```

**isomorphic-form-data.js**

```js
module.exports = globalThis.FormData
```

This will bypass the `ismorphic-form-data` library in your worker build fragment and will use `src/ismorphic-form-data.js` local file with correct global symbol. 

Please let me know if this temporary workaround worked for you.

**Comment by tmkasun** [comment] 2021-04-26 17:07
Thanks @char0n , I will check and let you know

**Comment by char0n** [comment] 2021-07-07 10:30
I've issued a [PR](https://github.com/form-data/isomorphic-form-data/pull/6) against https://github.com/form-data/isomorphic-form-data to fix this issue. Let's see if authors merge it and release a new major release.

**Comment by char0n** [comment] 2021-07-25 15:42
It's high time to fix this; isomorphic-form-data library looks completely dead and the fix is not going to come from upstream.

Here is a plan to resolving this issue in SwaggerJS repo:

1. wait for isomorphic support for formdata-node library (https://github.com/octet-stream/form-data/issues/38)
2. replace isomorphic-form-data for https://www.npmjs.com/package/formdata-node
3. release new version of swagger-client

More context here: https://github.com/swagger-api/swagger-js/pull/1547

After we have this resolved, swagger-client will be natively support in WebWorker env without workarounds provided in comments of this issue.

**Comment by char0n** [comment] 2021-07-27 09:35
Released in https://www.npmjs.com/package/swagger-client/v/3.14.0

**Closed by char0n** 2021-07-27 09:35 UTC
Labels: cat: usability, type: enhancement, version: 3.x
