### ISSUE TITLE
swagger-bot gone awry: node-14 tests failed but it wants the PR to still be merged

### ISSUE THREAD

**Issue by shazron** [swagger-api/swagger-js#3126] opened 2023-09-06 12:52 UTC
See https://github.com/swagger-api/swagger-js/pull/3118

Node-14 tests failed because `AggregateError`  is only defined in Node-15.

**Comment by char0n** [comment] 2023-09-07 11:50
Thanks for notice. This is duplicate of https://github.com/swagger-api/swagger-js/issues/3127

**Closed by char0n** 2023-09-07 11:50 UTC
Labels: type: support, version: 3.x
