### ISSUE TITLE
Client simply not posting provided data

### ISSUE THREAD

**Issue by Robbilie** [swagger-api/swagger-js#998] opened 2017-04-06 23:43 UTC
```
Swagger("https://esi.tech.ccp.is/latest/swagger.json")
  .then(client => client.apis.Universe.post_universe_names({ ids: [99005843] }));
```

now this is a post request, pasting  [99005843]  here : https://esi.tech.ccp.is/latest/#!/Universe/post_universe_names

yields the correct result, if you check the response in browser of the above code or go to http://petstore.swagger.io/ and use https://esi.tech.ccp.is/latest/swagger.json as the spec url you will realize it not working, the posted body is empty.

**Comment by Robbilie** [comment] 2017-04-06 23:59
moving on:
https://github.com/swagger-api/swagger-js/blob/master/README.md
search the readme for "addPet", copy & paste code and try to run it with:
http://petstore.swagger.io/v2/swagger.json

result:
Required parameter body is not provided

putting the body like it would be correct into an object with key body and value the value, as an object it returns:
415 (Unsupported Media Type)

cause no content-type nor body is sent

**Comment by webron** [comment] 2017-04-19 10:13
@Robbilie can you take a look at https://github.com/swagger-api/swagger-js/issues/1006? I suspect it's a duplicate of it.

**Comment by Robbilie** [comment] 2017-04-19 17:48
looked at it for 2 seconds and remembered: i tried "serializing" useing JSON.stringify but the result was that it was posted with content-type text and not json so it broke

**Closed** 2017-12-31 15:20 UTC
Labels: 3.x
