### ISSUE TITLE
Default scheme selection does not conform to spec

### ISSUE THREAD

**Issue by jbr** [swagger-api/swagger-js#950] opened 2017-02-21 22:11 UTC
According to the spec,
> If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself.

However in the following situation, swagger-js attempts to use http, instead of the scheme used to load the definition:
* using a recent swagger-js client (2.1.32)
* loading the static assets (window.location) over http
* loading the swagger definition over https
* not specifying `scheme` in client opts
* not specifying `schemes` in the definition

I believe that this is because https://github.com/swagger-api/swagger-js/blob/v2.1.32/lib/client.js#L352 does not have an `else`, so it immediately stomps https://github.com/swagger-api/swagger-js/blob/v2.1.32/lib/client.js#L350.  Happy to PR this, but wanted to confirm first that this was a bug.

**Comment by fehguy** [comment] 2017-02-21 22:14
yes, it's a bug.  If you can send a PR with some tests, will get it merged quickly.

**Comment by jbr** [comment] 2017-02-21 22:53
PR coming up.  I can't find an example in the code of mocking/stubbing global.window.  This potentially means may be other bugs like this.  Would you accept the addition of jsdom?

**Comment by jbr** [comment] 2017-02-27 23:29
@fehguy Following up on this: What is the preferred approach to testing code that is conditional on the presence of window.location? Should this be part of the karma-only suite, or should we use something like jsdom in the main suite?

**Comment by fehguy** [comment] 2017-03-02 02:08
Hi, I would add tests to the regular main tests to ensure the check for `window` and its properties does not break.  I would also add a test to the karma suite as you suggested to ensure that the check works and behaves.  Thank you for asking!

**Comment by Dewb** [comment] 2017-04-27 18:19
I'd like to add that even if you do specify `scheme` in the client opts in the above scenario when the swagger definition is loaded via `https`, the operations still incorrectly use `http` rather than `https` because the test in [line 348](https://github.com/swagger-api/swagger-js/blob/v2.1.32/lib/client.js#L348) needs to have parentheses around the second and third expressions.

**Comment by Dewb** [comment] 2017-04-27 19:47
Confirmed that https://github.com/Dewb/swagger-js/commit/409c395cc6a5348adaa36a4fb90d2145add7bfea fixes the above issue. I have not tested the OP's scenario.

**Comment by shockey** [comment] 2017-12-27 03:29
Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.

**Closed by shockey** 2017-12-27 03:29 UTC
Labels: 2.x
