### ISSUE TITLE
passive http transaction parsing

### ISSUE THREAD

**Issue by fantapop** [swagger-api/swagger-js#808] opened 2016-07-06 07:18 UTC
I'm interested in using swagger as a generic method of parsing api traffic that goes over the wire.  This seems to be a little different than the common use case and I'm wondering whether this would somehow already work or if it could be easily supported.

My ideal use case is to generate a be able to read in a swagger api definition file and output a parser in javascript. That javascript parser could then be used to parse an api http request into an object based on the swagger spec.

I already have the http content of the api requests.  I was considering whether it would be possible to use the custom http client functionality to get the parsed object based on local variables containing the headers, body, etc.

**Comment by fehguy** [comment] 2016-07-07 16:39
Well you probably can, but to be clear, that's definitely not what this library was intended for.  But I'm sure it has many other uses than it's original intent!

I'll close this out, and you can ask about specifics in new tickets.

**Closed by fehguy** 2016-07-07 16:39 UTC
