### ISSUE TITLE
Bug: Post request doesn't work with OpenAPI 3.0 in Alternative API

### ISSUE THREAD

**Issue by ZaharovDm** [swagger-api/swagger-js#1968] opened 2021-03-05 12:02 UTC
### Q&A (please complete the following information)
 - OS: [e.g. windows]
 - Environment: [e.g. Chrome 59, Node.js v10.0.0]
 - Method of installation: [e.g. npm]
 - Swagger-Client version: [e.g. 3.13.1]
 - Swagger/OpenAPI version: [e.g. OpenAPI 3.0.2]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
openapi: "3.0.2"
info:
  title: "Service API"
  description: "My service"
  version: "1.0.0"

servers:
  - url: "/api/v1"
    description: base url

paths:
  /reload_cache:
    post:
      tags:
        - system
      summary: "Reload cache"
      operationId: ReloadCache
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContextMode'
      responses:
        "200":
          description: OK
        "500":
          description: Reload cache failed

components:
  schemas:


    ContextMode:
      type: string
      enum:
        - pilot
        - files

```

Swagger-Client usage:
```js
import SwaggerClient from 'swagger-client';

let apiClient = {
    apiSpec: require("@/client-api/openapi.json")
}

var apiClient.swaggerClient = await SwaggerClient({spec: apiClient.apiSpec});

function reloadCache(mode) {
        return apiClient.swaggerClient.apis.system.ReloadCache(mode);
    }

```

### Describe the bug you're encountering
Swagger client creates request without body (in function "reloadCache"), and sends it to server.

Server returns:
Failed to load resource: the server responded with a status of 415 (Unsupported Media Type)

Because of that content-type value is empty.

### To reproduce...

1. OpenAPI v3.
2. Use your Alternate API
3. Post request

### Expected behavior
The body of the message must be sent, in alternative api

### Screenshots

![image](https://user-images.githubusercontent.com/17457553/110116967-500f2380-7dc9-11eb-900a-0b24b3a3f504.png)

### Additional context or thoughts

Most likely, this is due to the fact that when parsing method parameters in OpenAPI 3, the parameters of the request body do not need to be specified in the parameter block. 
parameters:
  - in: query/path/cookie/header (body deleted in openAPI v3)
 
During the analysis, the parameters of the request body are not found and then they are not taken into account and an empty message body is sent.

**Comment by char0n** [comment] 2021-03-05 16:09
I'll have a look during next week. Thanks for reporting it!

**Comment by dimitaracev** [comment] 2021-03-17 13:25
Having the same problem.

**Comment by char0n** [comment] 2021-03-26 12:51
I can confirm I was able to reproduce this. As a quick workaround I'd suggest to use [try-it-out-executor](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/try-it-out-executor.md#executing-an-operation). 

@ZaharovDm you already did a great job of debugging the problem, would you be interested in providing a bug fix?

**Comment by ZaharovDm** [comment] 2021-03-29 13:11
"As a quick workaround I'd suggest to use try-it-out-executor."

Saw a similar solution, this solution helped to solve the problem. But, I would like to have a solution through "Alternate API".

The original code didn't try to fix this. I have just put together some additional information for you that may make it easier to solve the problem.

**Comment by char0n** [comment] 2021-04-12 09:11
Hi @ZaharovDm,

Please have a look at [tags interface](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md#openapi-v3x) documentation. Basically in OAS3 definitions, request body must be passed as a property of second argument to tag interface function.

```js
import SwaggerClient from 'swagger-client';

new SwaggerClient({ spec, authorizations: { petstore_auth: { token: { access_token: '234934239' } } } })
  .then(client => 
    client
     .apis
     .pet // tag name == `pet`
     .addPet( // operationId == `addPet`
       { id: 1 },
       { // Options object
         requestBody: {
           name: 'bobby',
           status: 'available',
         },
         server: 'http://petstore.swagger.io/{apiPrefix}', // this should exactly match a URL in your `servers`
         serverVariables: {
           apiPrefix: 'v2'
         }
       }    
     )
  );
// => Promise.<Response>
```

**Comment by ZaharovDm** [comment] 2021-04-12 12:41
That is, if I have several "post" requests, each time I need to create a new one SwaggerClient?)

**Comment by char0n** [comment] 2021-04-12 14:44
> That is, if I have several "post" requests, each time I need to create a new one SwaggerClient?)

No need, you'll reuse the client instance and issue as much "operations" on it as you wish:

```js
import SwaggerClient from 'swagger-client';

new SwaggerClient({ spec, authorizations: { petstore_auth: { token: { access_token: '234934239' } } } })
  .then(client => 
    client
     .apis
     .pet // tag name == `pet`
     .addPet( // operationId == `addPet`
       { id: 1 },
       { // Options object
         requestBody: {
           name: 'bobby',
           status: 'available',
         },
         server: 'http://petstore.swagger.io/{apiPrefix}', // this should exactly match a URL in your `servers`
         serverVariables: {
           apiPrefix: 'v2'
         }
       }    
     )
  ) 
  .then(client => 
    client
     .apis
     .pet // tag name == `pet`
     .addPet( // operationId == `addPet`
       { id: 1 },
       { // Options object
         requestBody: {
           name: 'bobby',
           status: 'available',
         },
         server: 'http://petstore.swagger.io/{apiPrefix}', // this should exactly match a URL in your `servers`
         serverVariables: {
           apiPrefix: 'v2'
         }
       }    
     )
  );
// => Promise.<Response>
```

**Comment by ZaharovDm** [comment] 2021-04-13 08:02
I am interested in calling a service using methods in different parts of the code, it seems to me that the solution you suggest is a workaround.

**Comment by char0n** [comment] 2021-04-13 08:14
> I am interested in calling a service using methods in different parts of the code, it seems to me that the solution you suggest is a workaround.

Not at all. It was just a demonstration. I wasn't aware of your `reuse` usecase. For your particular usecase, the best approach would be to persist the swagger client instance in variable a reuse this variable in another places. Observe:

**client.js**
```js
import SwaggerClient from 'swagger-client';

let swaggerClient = null;

export const getClient = async () => {
  if (swaggerClient === null) { 
    swaggerClient = await new SwaggerClient({ spec, authorizations: { petstore_auth: { token: { access_token: '234934239' } } } });
  }

  return swaggerClient;
};
```

**usage1.js**
```js
import { getClient } from './client.js';

const addPet = async (data) => {
   const client = await getClient();  
   const response = await client.apis.pet.addPet({ }, { requestBody: data });

   return response;
};
```

**Comment by ZaharovDm** [comment] 2021-04-22 21:01
but the fact itself, there will be no fixes in the code that I found?

**Comment by char0n** [comment] 2021-04-23 09:44
Right, sorry closed this by accident, we need to fix request body generation.

**Comment by nvson2201** [comment] 2021-05-15 07:51
@ZaharovDm  the answer of char0n works

```js
 const response = await client.apis.pet.addPet({ }, { requestBody: data });
```

**Comment by char0n** [comment] 2021-05-17 07:53
At this point, IMHO we have no bug in this issue. Correct me if I'm wrong. In OAS 3.0.x request body needs to by provided as property of second argument to any `tag interface function` and when provided requests are generated properly. We have this clearly documented in documentation and I've provided additional info in this issue. 

Is there actually any problem that we need to provide bug-fix for?

**Comment by char0n** [comment] 2021-06-09 12:04
Closing for now as it was stipulated that this is not a bug but rather how API works with different versions of the OAS.

**Closed by char0n** 2021-06-09 12:04 UTC
Labels: type: bug, version: 3.x
