### ISSUE TITLE
Support for promises

### ISSUE THREAD

**Issue by nhagen** [swagger-api/swagger-js#207] opened 2015-01-18 01:57 UTC
Has there been any discussion on making this project work with promises, or any forks that have attempted this?

**Comment by fehguy** [comment] 2015-01-19 16:35
Yes, I'd like to do so but I want to avoid bringing in any large dependencies into the project.  Last I looked at it, we'd have to fatten up the library quite a bit to use common promise libs.  I know the JS world moves fast, so if we can bring lightweight support in, I'm all for it.

**Comment by fehguy** [comment] 2015-03-03 23:53
I'm going to move this to future, since it'll break current (client) api compatibility.  It is cleaner and will revisit in the future.

**Comment by mohsen1** [comment] 2015-03-04 00:07
It's easy to wrap callback based methods in a promise. You can use [`Q.nfcall`](https://github.com/kriskowal/q#using-deferreds) to use SwaggerJS with promises.

**Comment by marcellodesales** [comment] 2015-04-01 21:34
+1 for that... 

@mohsen1 Do you have examples on how to do that? I'm still learning about promises... 

I'm trying to use https://github.com/petkaantonov/bluebird...

**Comment by indolering** [comment] 2015-06-09 20:54
I would just like to point out that the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is slated for ES7 and its syntax will likely codify how responses are handled.  As much as I want Promise support ASAP, it's probably best to wait until the Fetch API syntax has stabilized.

But, FWIW, we will probably have to wait that long *anyway* since we have to wait for IE 11 to die before [Promise support](http://caniuse.com/#search=promise) is universal.  Github should have an IE glue-eater emoticon :rage:.

**Comment by mohsen1** [comment] 2015-06-09 21:13
I like the idea of using `window.fetch`. It has a good polyfill too

**Comment by indolering** [comment] 2015-06-12 20:56
@mohsen1 That would make it easier for you to produce a browser library without all of the weight that Browserify adds (50% of your minified codebase).

**Comment by mb21** [comment] 2015-06-30 11:46
What about using a lightweight promise library like [q](http://documentup.com/kriskowal/q/) (~2.5 KB minified and gzipped) and keeping the API backwards compatible by checking whether a callback function was provided or not.

With callbacks (backwards-compatible):

    var swagger = new client({
      url: 'http://petstore.swagger.io/v2/swagger.json',
      success: function() {
        swagger.pet.getPetById({petId:7},{responseContentType: 'application/json'},function(pet){
          console.log('pet', pet);
        });
      }
    });

Without callbacks (returns promises):

    new client({url: 'http://petstore.swagger.io/v2/swagger.json'}).then( function(swagger){
      swagger.pet.getPetById({petId:7},{responseContentType: 'application/json'}).then( function(pet){
        console.log('pet', pet);
      });
    });

**Comment by martinwoitzik** [comment] 2015-08-19 12:13
+1 for using q and providing a callback-fallback

**Comment by marcellodesales** [comment] 2015-08-21 17:27
I got it using Bluebirds

```js
var SwaggerClient = require("swagger-client");

function IntuitHttpClient(url) {
    return new Promise(function(resolve, reject) {
      var swagger = new SwaggerClient({url: url, success: function() {
        resolve(swagger);
      }});
    });
}
```

Calling the API should be something like:

```js

var url = "http://petstore.swagger.io/v2/swagger.json";

IntuitHttpClient(url).then(function(swagger) {
  // HTTP GET request. Taking HTTP_PROXY or https_proxy (or any case)
  // https://github.com/swagger-api/swagger-js#calling-an-api-with-swagger--nodejs

  console.log(swagger.apis);

  swagger.apis.pet.getPetById({petId:1}, function(pet) {
    console.log(pet.obj);
  });
});
```

**Comment by martinwoitzik** [comment] 2015-08-22 14:06
@marcellodesales You only wrapped the initialize function inside of a promise - not the api-calls!
I made a pull-request where everything can be fetched via promises as mentioned in the example of @mb21 .
If it gets merged, you just have to set the "usePromise"-flag to true if you want to use it.

**Comment by marcellodesales** [comment] 2015-08-24 02:09
@martinwoitzik you right... That would be great... I would definitely use it!

**Comment by indolering** [comment] 2015-08-24 22:03
I'm **strongly** against any non-standard promise implementations.  PouchDB [got rid of Bluebird](http://pouchdb.com/2015/08/03/pouchdb-4.0.0-ballast-overboard.html) because it encourages developers to use a non-standard API that they can't use anywhere else without importing Bluebird anyway.  Overtime, Bluebird's popularity will fade and we will be stuck packing around an extra 70KB (minified!) of code that no-one uses.

**Comment by martinwoitzik** [comment] 2015-08-26 12:45
@indolering does this also apply to my pull-request?

**Comment by indolering** [comment] 2015-08-26 17:28
@martinwoitzik Does Q introduce non-standard API?  I guess I would be okay with it if we only showed the standard API in official documentation and include a warning that Q will eventually get removed.

**Comment by mb21** [comment] 2015-08-27 08:35
Q implements [Promises/A+](https://promisesaplus.com/) and is basically compatible with [ES6 promises](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise), which is what the new fetch API returns, AFAIK.

**Comment by indolering** [comment] 2015-08-29 23:04
@mb21 basically or does?  I thinks it's fine to include it if the syntax conforms to the upcoming standard and it's clear that we will rip it out as soon as it's feasible to do so.  I would support removing the usePromise flag if we were using a polyfill that adhered strictly to ES6.

**Comment by indolering** [comment] 2015-10-24 23:55
After trying to write some error handling code, I'm strongly for pushing this through ASAP.  I think we should add a warning regarding any non-standard behaviors, but I'm fine with it in the short term.

**Comment by jacobrask** [comment] 2015-11-01 20:04
My preference would be to use native promises, and let users include a [polyfill](https://github.com/jakearchibald/es6-promise) of their own choice. Native promises are supported by the latest versions of all major browsers and are as @mb21 says what the fetch API returns.

In our application we already include a Promise polyfill for users of IE11, another promise implementation is an unnecessary download for the user.

**Comment by indolering** [comment] 2015-11-05 02:43
@jacobrask I'm guessing that part of the problem is the need to simultaneously support multiple callback styles.  Q can handle JQuery deferreds and I assume that is how they added support.  I agree native promises are the right way to go but that requires a lot of effort.

**Comment by indolering** [comment] 2015-12-08 20:33
This has been pushed to production, should be closed.

**Closed** 2015-12-09 03:18 UTC

**Comment by SunboX** [comment] 2016-07-22 07:09
Would love to see Promises in Swagger generated JavaScript Client. There are a lot of Polyfills for older Browsers. So anyone can choose what he want's to implement (or already has implemented).

**Comment by fehguy** [comment] 2016-07-22 14:46
Please open this on swagger-codegen then, @SunboX.  This project does support promises.

**Comment by wing328** [comment] 2016-07-22 14:52
@SunboX To generate JS API client with Promise support (using Swagger Codegen), you will need to provide `--additional-properties usePromises=true`

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/bin/javascript-promise-petstore.sh#L32

Please use the latest version (2.2.0) of Swagger Codegen to give it a try.
