### ISSUE TITLE
POST with path, query and body, had to 'hard-code' content-type to avoid 415

### ISSUE THREAD

**Issue by kleindev** [swagger-api/swagger-js#1096] opened 2017-06-28 02:44 UTC
I'm using 3.0.16 in the browser.  I believe the issue may be that I'm going off on 2.x google-example, but I'm unclear on how I can specify the content-type to be application/json on given operations.

I hacked up swagger-client.js and added the content-type as a default header.  I've tried different options of adding { "requestContentType": "application/json"} as a parameter.  If I try to stringify the parameters, then the path parameters get missed.

I fully suspect this is user error on my part - looking for guidance on how to set the content-type.

**Comment by webron** [comment] 2017-06-28 06:11
Did you set the `consumes` for the operation?
Can you share your API definition?

**Comment by kleindev** [comment] 2017-06-28 06:35
Good point, very well could be something I need to adjust on the definition.  I do have a `consumes` defined - multiple though.  Perhaps I could remove all but application/json.  Here is a snippet for the particular operation:


"/v1/customers/{customerId}/alerts/search": {
      "post": {
        "tags": [ "Alerts" ],
        "operationId": "V1CustomersByCustomerIdAlertsSearchPost",
        "consumes": [ "application/json", "text/json", "application/json-patch+json" ],
        "produces": [ "text/plain", "application/json", "text/json" ],
        "parameters": [
          {
            "name": "customerId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "since",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "date-time"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "continuationToken",
            "in": "body",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "name": "X-AMOC-KEY",
            "in": "header",
            "description": "userid:apikey",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/PagedResults[Alert]" }
            }
          },
          "403": { "description": "Forbidden" },
          "500": { "description": "Server Error" }
        }
      }
    }
`"/v1/customers/{customerId}/alerts/search": {
"post": {
        "tags": [ "Alerts" ],
        "operationId": "V1CustomersByCustomerIdAlertsSearchPost",
        "consumes": [ "application/json", "text/json", "application/json-patch+json" ],
        "produces": [ "text/plain", "application/json", "text/json" ],
        "parameters": [
          {
            "name": "customerId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "since",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "date-time"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "continuationToken",
            "in": "body",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "name": "X-AMOC-KEY",
            "in": "header",
            "description": "userid:apikey",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/PagedResults[Alert]" }
            }
          },
          "403": { "description": "Forbidden" },
          "500": { "description": "Server Error" }
        }
      }
    }`

**Comment by kleindev** [comment] 2017-06-28 17:07
I believe I found a way to get it to work.  My body parameter is optional - if I pass a value there, the client will work as my API expects (application/json content type).

**Comment by fehguy** [comment] 2017-06-28 17:08
Ah yes, I've seen that before, where an empty JSON body is actually invalid unless it's an "empty json object" (`{}`).  That was sent by the previous version but this must be a regression in the 3.x series.

**Comment by webron** [comment] 2017-06-28 20:21
This is related to #1022. In short, if no payload is being sent, there's no reason to send the `content-type` header.

**Comment by shockey** [comment] 2017-11-29 08:01
<img src='https://shipusercontent.com/3648699216bc32ad031c6a59920adfa5/Pasted%20Image%201.png' title='Pasted Image 1.png' width=570>

Looks like latest Swagger-Client omits `Content-Type` with empty bodies. Closing!

**Closed by shockey** 2017-11-29 08:01 UTC
