### ISSUE TITLE
fresh of swagger has unmet dependencies

### ISSUE THREAD

**Issue by srl295** [swagger-api/swagger-js#1326] opened 2018-05-26 15:41 UTC
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Node 8.11.2
 - Method of installation: npm
 - Swagger-Client version: 3.8.5
 - Swagger/OpenAPI version: n/a

### Swagger-Client usage:
```js
require('swagger-client')
```

### Describe the bug you're encountering
```
Error: Cannot find module 'base64-js'
```

Manually adding that module caused a "cannot find module `ieee754`.

### To reproduce...

```
mkdir /tmp/junk
cd /tmp/junk
nvm i 8.11.2
npm init -q -y
npm install swagger-client
node -p "require('swagger-client')"
```
### Expected behavior
probably nothing, no error message

### Additional context or thoughts
I hit this by removing my `package-lock.json` and trying to rebuild it, chasing a lodash dependency issue.

**Comment by srl295** [comment] 2018-05-26 15:41
gist here https://gist.github.com/srl295/782b21a24f70f963fefb541e23373984

**Comment by shockey** [comment] 2018-05-26 22:30
Thanks @srl295, going to look into this now.

**Comment by vrsbrazil** [comment] 2018-05-28 14:20
Is there a swagger-client version where this is not happening?

**Comment by vrsbrazil** [comment] 2018-05-28 15:38
# FOUND DEPENDENCY ERROR

It is the deep-extend 0.6.0 version that is breaking the code, changed the package.json version to fixed 0.5.1 at the swagger-client and it worked.

**Comment by shockey** [comment] 2018-05-28 19:08
Okay, I've been chasing this for a while and haven't nailed it down yet. This appears to be new in 3.8.5, I can require prior versions just fine.

Firstly, I haven't been able to reproduce this in my local environment yet - it looks like Swagger-Client's development dependencies do pull in `base64-js`, so it's hard to run tests or build locally for this. 

Second... only one production dependency mentions `base64-js` at all:

```
➜  js git:(master) ag -l "base64-js" ./node_modules     
node_modules/fast-json-patch/package-lock.json
```

This is a `package-lock.json`, which shouldn't be in published packages at all - but beyond that, [`fast-json-patch`](https://www.npmjs.com/package/fast-json-patch) hasn't released in 7 months, and we didn't change any usage of it last week, so it's very unlikely that this is the cause.

---



In fact, we changed very little in Swagger-Client last week ([diff](https://github.com/swagger-api/swagger-js/compare/v3.8.4...master)). 

My intuition is that usage of the `Buffer` global triggered this, since the [`buffer`](https://www.npmjs.com/package/buffer) module only has `base64-js` and `ieee754` as dependencies, but I don't have a stack trace to back that up.

Needing to add that module as a dependency is at odds with what I'd expect: Webpack's `NodeSourcePlugin` should transparently polyfill the Buffer global since we're using the web target by default.

**Comment by vrsbrazil** [comment] 2018-05-28 19:21
@shockey the error is only triggered when the swagger-client is used as a module on a different project, as I mentioned before, the error goes away once I got straight to the swagger-client at my node_modules and run npm install in it, so I believe you have a dependency reference issue somewhere...

**Closed** 2018-05-28 19:27 UTC

**Comment by shockey** [comment] 2018-05-28 19:51
@vrsbrazil yeah, it looks like our development dependencies were incidentally adding the necessary modules to `node_modules`, which was keeping this from busting our CI.

---

This appears fixed from my end - I'm able to require `swagger-client@3.8.6`.

Please let me know if there are any lingering issues!
