### ISSUE TITLE
Inline response schemas not supported in 2.1 UI

### ISSUE THREAD

**Issue by hamx0r** [swagger-api/swagger-js#518] opened 2015-07-07 21:39 UTC
This bug matches issue #189 , but for 2.1 instead of 2.0

I'm seeing inline schema support disappeared in v2.1.0.  Inline Response schemas specifically disappeared in Swagger UI in 

 - develop branch 59459a608608b62a9a02e1993dd773f934767953
 - [official release 2.1.0](https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.0)

Tested with the below, where the referenced `Error` schema shows in UI fine, but inline 403 response does not:

    "responses": {
          "200": {
            "description": "X-Identity-Token retrieved", 
            "schema": {
              "properties": {
                "authId": {
                  "type": "string"
                }
              }
            }
          }, 
          "401": {
            "description": "Unauthorized", 
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }, 
          "403": {
            "description": "Forbidden", 
            "schema": {
              "description": "General error response form", 
              "properties": {
                "message": {
                  "default": "Forbidden", 
                  "type": "string"
                }, 
                "status": {
                  "default": 403, 
                  "type": "integer"
                }
              }, 
              "required": [
                "status", 
                "message"
              ]
            }
          }, 
          "500": {
            "description": "Internal Server Error", 
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }

![image](https://cloud.githubusercontent.com/assets/423974/8557765/6081ce10-24f7-11e5-9a27-6bbc3ebd110b.png)

**Comment by PavelPolyakov** [comment] 2016-01-14 16:03
@fehguy 

Hi,

We just met that issue.
And I see that milestone for that bug is postponed over and over.

Is that ok that inline schemas are not supported? Because it's seems to be logical, to have an option to describe the schema in line, not referencing the defined objects.

**Comment by fehguy** [comment] 2016-01-14 19:11
Hmm.  I am sorry, this should have been either fixed in the last release, or tested and marked as such.  Do you mind retesting and reporting back?  I did redo the response processing to fix #681 so this may be fixed as an artifact of that.

**Comment by fehguy** [comment] 2016-06-10 03:29
this is confirmed working.

**Closed by fehguy** 2016-06-10 03:29 UTC
Labels: Bug, P1, Regression
